apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp-demo-ingress
  namespace: webapp-demo
  annotations:
    # cert-manager.io/issuer: "letsencrypt"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/proxy-body-size: "32m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300" 
spec:
  rules:
  - http:
      paths:
      - path: /webapp
        backend:
          serviceName: webapp-demo-service
          servicePort: 80